import React from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, FileText } from 'lucide-react';

const Terms = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-[#0A0A0C] text-gray-300 font-sans selection:bg-red-500/30 selection:text-white">
      {/* Navigation Header */}
      <nav className="border-b border-gray-800/50 bg-[#0A0A0C]/90 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-4 h-16 flex items-center justify-between">
          <button 
            onClick={() => navigate('/')}
            className="flex items-center gap-2 text-sm font-semibold text-gray-400 hover:text-white transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </button>
          <div className="font-extrabold text-white text-lg tracking-wider">
            MOTOGP MANAGER
          </div>
        </div>
      </nav>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-4 py-16">
        <div className="flex items-center gap-4 mb-10">
          <div className="p-4 bg-orange-500/10 rounded-2xl border border-orange-500/20 text-orange-500">
            <FileText className="w-8 h-8" />
          </div>
          <div>
            <h1 className="text-4xl font-black text-white">Terms of Service</h1>
            <p className="text-gray-500 mt-1">Last updated: July 2026</p>
          </div>
        </div>

        <div className="space-y-8 text-gray-400 leading-relaxed bg-[#16161C] p-8 md:p-12 rounded-3xl border border-gray-800 shadow-xl">
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and playing MotoGP Manager MVP, you accept and agree to be bound by the terms and 
              provisions of this agreement. If you do not agree to abide by these terms, you should not 
              use this service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">2. Account Registration and Rules</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>You must provide a valid email address and secure password to create an account.</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You agree not to use automated scripts, bots, or exploit bugs to gain an unfair advantage in the simulation.</li>
              <li>Administrators reserve the right to ban or suspend accounts found violating fair play guidelines.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">3. Gameplay and Simulation Engine</h2>
            <p>
              MotoGP Manager MVP relies on a customized physics and simulation engine to calculate race results. 
              The results generated by the engine are final. We do not guarantee uninterrupted uptime of the 
              simulation servers, and maintenance periods may occur without prior notice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">4. User Content</h2>
            <p>
              Users may create championships and teams. You agree not to use offensive, defamatory, or 
              inappropriate language for usernames, team names, or championship names. The administrators 
              reserve the right to rename or delete content deemed inappropriate.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">5. Modifications to Service</h2>
            <p>
              We reserve the right to modify or discontinue, temporarily or permanently, the service (or any 
              part of it) with or without notice. We shall not be liable to you or to any third party for any 
              modification, suspension, or discontinuance of the service.
            </p>
          </section>
        </div>
      </main>

      <footer className="py-8 text-center text-gray-600 text-sm">
        © {new Date().getFullYear()} MotoGP Manager MVP. All rights reserved.
      </footer>
    </div>
  );
};

export default Terms;
